test for file

diff --git a/.github/workflows/release-observability-images.yaml b/.github/workflows/release-observability-images.yaml
--- a/.github/workflows/release-observability-images.yaml
+++ b/.github/workflows/release-observability-images.yaml
@@ -22,23 +22,19 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
-      - name: Test
-        run: |
-          
-          cat .github/shared-variables/.env
-          echo "after"
-          cat ${{ env.ENV_FILE_PATH }}
-
       - name: Load and Increment OBSERVABILITY_VERSION
         run: |
-          ls -a .github/shared-variables
+          if [ ! -f  ${{ env.ENV_FILE_PATH }} ]; then
+            echo "${{ env.ENV_FILE_PATH }} file not found!"
+            exit 1
+          fi
           OBSERVABILITY_VERSION=$(grep '^OBSERVABILITY_VERSION=' .github/shared-variables/.env | cut -d '=' -f2)
           if [ -z "$OBSERVABILITY_VERSION" ]; then
             echo "OBSERVABILITY_VERSION not found in .${{ env.ENV_FILE_PATH }}!"
             exit 1
           fi
           NEW_VERSION=$(printf "%05d" $((10#$OBSERVABILITY_VERSION + 1)))
-          sed -i "s/^OBSERVABILITY_VERSION=.*/OBSERVABILITY_VERSION=${NEW_VERSION}/" .env
+          sed -i "s/^OBSERVABILITY_VERSION=.*/OBSERVABILITY_VERSION=${NEW_VERSION}/" ${{ env.ENV_FILE_PATH
           echo::notice::"OBSERVABILITY_VERSION=${NEW_VERSION}"
 
       - name: Commit and Push Changes
