test observability image generation

diff --git a/.github/workflows/release-node-images.yaml b/.github/workflows/release-node-images.yaml
--- a/.github/workflows/release-node-images.yaml
+++ b/.github/workflows/release-node-images.yaml
@@ -3,18 +3,18 @@ name: Create and upload packer generated images
 on:
   push:
     tags:
-      - 'node/*.*.*-rc'
-      - 'node/*.*.*-alpha'
+      - 'node/*.*.*-*-rc'
+      - 'node/*.*.*-*-alpha'
 
 env:
   PACKER_VERSION: "latest"
   AWS_ROLE_ARN: "arn:aws:iam::192549843005:role/github-devops-cd"
-  OBSERVABILITY_AWS_REGION: "eu-west-1"
   IMAGE_COUNT_UPPER_LIMIT: 20
   IMAGE_COUNT_LOWER_LIMIT: 10
   PROJECT_NAME: ConcordiumNode
   ENVIRONMENT_TO_AWS_REGION: '{"stagenet":"eu-west-1", "testnet":"eu-central-1", "mainnet":"eu-central-1", "flynet":"eu-west-1"}'
   REGION_TO_SUBNET: '{"eu-west-1": "subnet-0420e07bd378fc8ef", "eu-central-1": "subnet-018c28ad04a57702e" }'
+  NODE_VERSION: 'node/7.0.6-5-alpha'
 
 permissions:
   id-token: write
@@ -124,14 +124,74 @@ jobs:
         id: image_id
         run: echo "image_id_${{ matrix.cloud_provider }}=$IMAGE_ID" >> $GITHUB_OUTPUT
 
+  generate-matrix:
+    runs-on: ubuntu-latest
+    needs: [validate-preconditions]
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+    steps:
+      - name: Initialize Matrix with alpha environments
+        run: |
+          MATRIX_JSON=$(echo '[
+            {
+              "env": "stagenet",
+              "tld": "com",
+              "cloud_provider": "aws",
+            },
+            {
+              "env": "flynet",
+              "tld": "com",
+              "cloud_provider": "aws",
+            },
+            {
+              "env": "stagenet",
+              "tld": "com",
+              "cloud_provider": "gcp",
+            }
+          ]' | jq -c)
+          echo "MATRIX_JSON=${MATRIX_JSON}" >> $GITHUB_ENV
+
+      - name: Release candidate environments
+        if: needs.validate-preconditions.outputs.release_type == 'rc'
+        run: |
+          MATRIX_JSON=$(echo "$MATRIX_JSON" | jq -c '. + [
+            {
+              "env": "testnet",
+              "tld": "com",
+              "cloud_provider": "aws"
+            },
+            {
+              "env": "testnet",
+              "tld": "com",
+              "cloud_provider": "gcp"
+            },
+            {
+              "env": "mainnet",
+              "tld": "software",
+              "cloud_provider": "aws",
+              "ami_users": '["727113945353"]'
+            },
+            {
+              "env": "mainnet",
+              "tld": "software",
+              "cloud_provider": "gcp"
+            },
+          ]')
+          echo "MATRIX_JSON=${MATRIX_JSON}" >> $GITHUB_ENV
+
+      - name: Output Matrix JSON
+        id: set-matrix
+        run: echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
+
+
   release-concordium-node-image:
     outputs:
       image_name_gcp_stagenet: ${{ steps.image_name.outputs.image_name_gcp_stagenet }}
-      image_name_gcp_testnet: ${{ steps.image_name.outputs.image_name_gcp_testnet }}
-      image_name_gcp_mainnet: ${{ steps.image_name.outputs.image_name_gcp_mainnet }}
+#      image_name_gcp_testnet: ${{ steps.image_name.outputs.image_name_gcp_testnet }}
+#      image_name_gcp_mainnet: ${{ steps.image_name.outputs.image_name_gcp_mainnet }}
       image_name_aws_stagenet: ${{ steps.image_name.outputs.image_name_aws_stagenet }}
-      image_name_aws_testnet: ${{ steps.image_name.outputs.image_name_aws_testnet }}
-      image_name_aws_mainnet: ${{ steps.image_name.outputs.image_name_aws_mainnet }}
+#      image_name_aws_testnet: ${{ steps.image_name.outputs.image_name_aws_testnet }}
+#      image_name_aws_mainnet: ${{ steps.image_name.outputs.image_name_aws_mainnet }}
       image_name_aws_flynet: ${{ steps.image_name.outputs.image_name_aws_flynet }}
     needs: [release-observability-image]
     environment: release-images
@@ -139,29 +199,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        include:
-          - env: flynet
-            tld: com
-            cloud_provider: aws
-          - env: stagenet
-            tld: com
-            cloud_provider: aws
-          - env: testnet
-            tld: com
-            cloud_provider: aws
-          - env: mainnet
-            tld: software
-            cloud_provider: aws
-            ami_users: '["727113945353"]'
-          - env: stagenet
-            tld: com
-            cloud_provider: gcp
-          - env: testnet
-            tld: com
-            cloud_provider: gcp
-          - env: mainnet
-            tld: software
-            cloud_provider: gcp
+        include: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
     defaults:
       run:
         working-directory: ./packer
@@ -255,96 +293,96 @@ jobs:
       run: |
         echo "image_name_${{ matrix.cloud_provider }}_${{ matrix.env }}=$IMAGE_NAME" >> $GITHUB_OUTPUT
 
-  notify-slack-changes:
-    needs: [release-observability-image, release-concordium-node-image]
-    environment: release-images
-    runs-on: ubuntu-latest
-    if: ${{ always() }}
-    steps:
-    - name: Sample updated Image IDs
-      run: |
-        echo '${{ toJson(needs.release-concordium-node-image.outputs) }}' > info.json
-        UPDATED_IMAGE_IDS=$(cat info.json | jq -c \
-          --arg el1 $(echo '${{ toJson(needs.release-observability-image.outputs) }}' | jq -r .image_name_gcp) \
-          --arg el2 $(echo '${{ toJson(needs.release-observability-image.outputs) }}' | jq -r .image_name_aws) \
-          '. + (if $el1 != "" and ($el1 != "null") then {"image_name_gcp_observability": $el1 } else {} end) + (if $el2 != "" and ($el2 != "null") then {"image_name_aws_observability": $el2 } else {} end)' | jq -R | sed 's/^"//;s/"$//')
-        echo "UPDATED_IMAGE_IDS=$UPDATED_IMAGE_IDS" >> $GITHUB_ENV
-    - name: Send updated image ids to slack
-      if: ${{ env.UPDATED_IMAGE_IDS != '{}' && env.UPDATED_IMAGE_IDS != '' }}
-      uses: slackapi/slack-github-action@v1.25.0
-      with:
-        payload: >-
-          {
-            "text": "The following image ids has been updated: ${{ env.UPDATED_IMAGE_IDS }}"
-          }
-      env:
-        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_URL }}
-
-  fetch-images:
-    needs: [release-concordium-node-image]
-    runs-on: ubuntu-latest
-    environment: release-images
-    outputs:
-      images: ${{ steps.fetch-images.outputs.images }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Configure GCP credentials
-        uses: google-github-actions/auth@v2
-        with:
-          project_id: concordium-mgmt-0
-          workload_identity_provider: projects/761241104197/locations/global/workloadIdentityPools/github/providers/concordium
-          service_account: github-devops-cd@concordium-mgmt-0.iam.gserviceaccount.com
-
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-region: ${{ env.OBSERVABILITY_AWS_REGION }}
-          role-to-assume: ${{ env.AWS_ROLE_ARN }}
-          role-session-name: ReleaseConcordiumNodeImageSession
-
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.11'
-
-      - name: Fetch images to be deleted
-        id: fetch-images
-        run: |
-          set -e
-          TARGET_AWS_REGIONS=$(echo '${{ env.ENVIRONMENT_TO_AWS_REGION }}' | jq -r -c '[..|strings]|unique| join(" ")')
-          IMAGES=$(python tools/find_images.py --image_count_lower_limit ${{ env.IMAGE_COUNT_LOWER_LIMIT }} --image_count_upper_limit ${{ env.IMAGE_COUNT_UPPER_LIMIT }} --aws_regions $TARGET_AWS_REGIONS)
-          echo "images=$(echo $IMAGES | jq '@json' | sed 's/^"\(.*\)"$/\1/')" >> $GITHUB_OUTPUT
-
-  notify-slack-on-image-deletions:
-    needs: [fetch-images]
-    environment: release-images
-    runs-on: ubuntu-latest
-    if: ${{ needs.fetch-images.outputs.images != '{}' }}
-    steps:
-      - name: Send GitHub Action trigger data to Slack workflow
-        uses: slackapi/slack-github-action@v1.25.0
-        with:
-          payload: >-
-            {
-              "text": "There are image which should be deleted: ```$DEVOPS_REPOSITORY_PATH/tools/delete_amis.sh '${{ needs.fetch-images.outputs.images }}'```"
-            }
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_URL }}
-
-  notify-slack-on-failure:
-    needs: [release-observability-image, release-concordium-node-image]
-    environment: release-images
-    runs-on: ubuntu-latest
-    if: ${{ failure() }}
-    steps:
-      - name: Send GitHub Action trigger data to Slack workflow
-        uses: slackapi/slack-github-action@v1.25.0
-        with:
-          payload: >-
-            {
-              "text": "One or more GitHub Actions jobs failed: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Click here> to see the run."
-            }
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_URL }}
+#  notify-slack-changes:
+#    needs: [release-observability-image, release-concordium-node-image]
+#    environment: release-images
+#    runs-on: ubuntu-latest
+#    if: ${{ always() }}
+#    steps:
+#    - name: Sample updated Image IDs
+#      run: |
+#        echo '${{ toJson(needs.release-concordium-node-image.outputs) }}' > info.json
+#        UPDATED_IMAGE_IDS=$(cat info.json | jq -c \
+#          --arg el1 $(echo '${{ toJson(needs.release-observability-image.outputs) }}' | jq -r .image_name_gcp) \
+#          --arg el2 $(echo '${{ toJson(needs.release-observability-image.outputs) }}' | jq -r .image_name_aws) \
+#          '. + (if $el1 != "" and ($el1 != "null") then {"image_name_gcp_observability": $el1 } else {} end) + (if $el2 != "" and ($el2 != "null") then {"image_name_aws_observability": $el2 } else {} end)' | jq -R | sed 's/^"//;s/"$//')
+#        echo "UPDATED_IMAGE_IDS=$UPDATED_IMAGE_IDS" >> $GITHUB_ENV
+#    - name: Send updated image ids to slack
+#      if: ${{ env.UPDATED_IMAGE_IDS != '{}' && env.UPDATED_IMAGE_IDS != '' }}
+#      uses: slackapi/slack-github-action@v1.25.0
+#      with:
+#        payload: >-
+#          {
+#            "text": "The following image ids has been updated: ${{ env.UPDATED_IMAGE_IDS }}"
+#          }
+#      env:
+#        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_URL }}
+#
+#  fetch-images:
+#    needs: [release-concordium-node-image]
+#    runs-on: ubuntu-latest
+#    environment: release-images
+#    outputs:
+#      images: ${{ steps.fetch-images.outputs.images }}
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Configure GCP credentials
+#        uses: google-github-actions/auth@v2
+#        with:
+#          project_id: concordium-mgmt-0
+#          workload_identity_provider: projects/761241104197/locations/global/workloadIdentityPools/github/providers/concordium
+#          service_account: github-devops-cd@concordium-mgmt-0.iam.gserviceaccount.com
+#
+#      - name: Configure AWS Credentials
+#        uses: aws-actions/configure-aws-credentials@v4
+#        with:
+#          aws-region: ${{ env.OBSERVABILITY_AWS_REGION }}
+#          role-to-assume: ${{ env.AWS_ROLE_ARN }}
+#          role-session-name: ReleaseConcordiumNodeImageSession
+#
+#      - name: Set up Python
+#        uses: actions/setup-python@v5
+#        with:
+#          python-version: '3.11'
+#
+#      - name: Fetch images to be deleted
+#        id: fetch-images
+#        run: |
+#          set -e
+#          TARGET_AWS_REGIONS=$(echo '${{ env.ENVIRONMENT_TO_AWS_REGION }}' | jq -r -c '[..|strings]|unique| join(" ")')
+#          IMAGES=$(python tools/find_images.py --image_count_lower_limit ${{ env.IMAGE_COUNT_LOWER_LIMIT }} --image_count_upper_limit ${{ env.IMAGE_COUNT_UPPER_LIMIT }} --aws_regions $TARGET_AWS_REGIONS)
+#          echo "images=$(echo $IMAGES | jq '@json' | sed 's/^"\(.*\)"$/\1/')" >> $GITHUB_OUTPUT
+#
+#  notify-slack-on-image-deletions:
+#    needs: [fetch-images]
+#    environment: release-images
+#    runs-on: ubuntu-latest
+#    if: ${{ needs.fetch-images.outputs.images != '{}' }}
+#    steps:
+#      - name: Send GitHub Action trigger data to Slack workflow
+#        uses: slackapi/slack-github-action@v1.25.0
+#        with:
+#          payload: >-
+#            {
+#              "text": "There are image which should be deleted: ```$DEVOPS_REPOSITORY_PATH/tools/delete_amis.sh '${{ needs.fetch-images.outputs.images }}'```"
+#            }
+#        env:
+#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_URL }}
+#
+#  notify-slack-on-failure:
+#    needs: [release-observability-image, release-concordium-node-image]
+#    environment: release-images
+#    runs-on: ubuntu-latest
+#    if: ${{ failure() }}
+#    steps:
+#      - name: Send GitHub Action trigger data to Slack workflow
+#        uses: slackapi/slack-github-action@v1.25.0
+#        with:
+#          payload: >-
+#            {
+#              "text": "One or more GitHub Actions jobs failed: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Click here> to see the run."
+#            }
+#        env:
+#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_URL }}
