fix issues unloaded variables

diff --git a/.github/workflows/release-node-images.yaml b/.github/workflows/release-node-images.yaml
--- a/.github/workflows/release-node-images.yaml
+++ b/.github/workflows/release-node-images.yaml
@@ -117,97 +117,99 @@ jobs:
       run:
         working-directory: ./packer
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
-    - name: Configure GCP credentials
-      uses: google-github-actions/auth@v2
-      with:
-        project_id: concordium-mgmt-0
-        workload_identity_provider: projects/761241104197/locations/global/workloadIdentityPools/github/providers/concordium
-        service_account: github-devops-cd@concordium-mgmt-0.iam.gserviceaccount.com
-    - name: Setup AWS REGION
-      run: |
-        VALUE=$(echo '${{ env.ENVIRONMENT_TO_AWS_REGION }}' | jq -r --arg key "${{ matrix.env }}" '.[$key]')
-        if [[ $VALUE == "null" ]]; then
-          echo "Key '${{ matrix.env }}' not found in ${{ env.ENVIRONMENT_TO_AWS_REGION }}"
-          exit 1
-        fi
-        echo "AWS_ENVIRONMENT_REGION=$VALUE" >> $GITHUB_ENV
-    - name: Setup subnet id
-      if: ${{ matrix.cloud_provider == 'aws' }}
-      run: |
-        VALUE=$(echo '${{ env.REGION_TO_SUBNET }}' | jq -r --arg key "${{ env.AWS_ENVIRONMENT_REGION }}" '.[$key]')
-        if [[ $VALUE == "null" ]]; then
-          echo "Key '${{ env.AWS_ENVIRONMENT_REGION }}' not found in ${{ env.REGION_TO_SUBNET }}"
-          exit 1
-        fi
-        echo "SUBNET_ID=$VALUE" >> $GITHUB_ENV
-    - name: Configure AWS Credentials
-      uses: aws-actions/configure-aws-credentials@v4
-      with:
-        aws-region: ${{ env.AWS_ENVIRONMENT_REGION }}
-        role-to-assume: ${{ env.AWS_ROLE_ARN }}
-        role-session-name: ReleaseConcordiumNodeImageSession
-    - name: Download file from S3
-      run: |
-        aws s3 cp s3://distribution.${{ matrix.env }}.concordium.${{ matrix.tld }}/deb/concordium-${{ matrix.env }}-node_${{ env.CONCORDIUM_NODE_VERSION }}_amd64.deb ./concordium-node.deb
-    - name: Setup image name
-      run: |
-        if [ "${{ matrix.cloud_provider }}" == "aws" ]; then
-          echo "IMAGE_NAME=${{ matrix.env }}-${{ env.CONCORDIUM_NODE_VERSION }}-concordium-node-${{ env.OBSERVABILITY_VERSION }}-x86_64" >> $GITHUB_ENV
-        elif [ "${{ matrix.cloud_provider }}" == "gcp" ]; then
-          VERSION_TRANSFORMED=${CONCORDIUM_NODE_VERSION//./-}
-          echo "IMAGE_NAME=${{ matrix.env }}-v$VERSION_TRANSFORMED-concordium-node-${{ env.OBSERVABILITY_VERSION }}-x86-64" >> $GITHUB_ENV
-        else
-          echo "Unknown cloud provider: ${{ matrix.cloud_provider }}"
-          exit 1
-        fi
-    - name: Test if image exists
-      run: |
-        if [ "${{ matrix.cloud_provider }}" == "aws" ]; then
-          echo "IMAGE_ID=$(aws ec2 describe-images --filters Name=name,Values=$IMAGE_NAME --query 'Images[*].ImageId' --output text)" >> $GITHUB_ENV
-        elif [ "${{ matrix.cloud_provider }}" == "gcp" ]; then
-          echo "IMAGE_ID=$(gcloud compute images list --project="concordium-${{ matrix.env }}-0" --filter="name=($IMAGE_NAME)" --format="value(name)")" >> $GITHUB_ENV
-        else
-          echo "Unknown cloud provider: ${{ matrix.cloud_provider }}"
-          exit 1
-        fi
-    - name: Set source image id
-      if: ${{ env.IMAGE_ID == '' }}
-      run: |
-        if [ "${{ matrix.cloud_provider }}" == "aws" ]; then
-          SOURCE_IMAGE_ID=$(aws ec2 describe-images --filters Name=name,Values=concordium-observability-node-${{ env.OBSERVABILITY_VERSION }}-x86_64 --query 'Images[*].ImageId' --output text)
-        elif [ "${{ matrix.cloud_provider }}" == "gcp" ]; then
-          SOURCE_IMAGE_ID=$(gcloud compute images list --project="concordium-mgmt-0" --filter="name=(concordium-observability-node-${{ env.OBSERVABILITY_VERSION }}-x86-64)" --format="value(name)")
-        else
-          echo "Unknown cloud provider: ${{ matrix.cloud_provider }}"
-          exit 1
-        fi
-        echo "SOURCE_IMAGE_ID=$SOURCE_IMAGE_ID" >> $GITHUB_ENV
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Load common variables
+        run: cat ../.github/shared-variables/.env >> $GITHUB_ENV
+      - name: Configure GCP credentials
+        uses: google-github-actions/auth@v2
+        with:
+          project_id: concordium-mgmt-0
+          workload_identity_provider: projects/761241104197/locations/global/workloadIdentityPools/github/providers/concordium
+          service_account: github-devops-cd@concordium-mgmt-0.iam.gserviceaccount.com
+      - name: Setup AWS REGION
+        run: |
+          VALUE=$(echo '${{ env.ENVIRONMENT_TO_AWS_REGION }}' | jq -r --arg key "${{ matrix.env }}" '.[$key]')
+          if [[ $VALUE == "null" || $VALUE == "" ]]; then
+            echo "Key '${{ matrix.env }}' not found in ${{ env.ENVIRONMENT_TO_AWS_REGION }}"
+            exit 1
+          fi
+          echo "AWS_ENVIRONMENT_REGION=$VALUE" >> $GITHUB_ENV
+      - name: Setup subnet id
+        if: ${{ matrix.cloud_provider == 'aws' }}
+        run: |
+          VALUE=$(echo '${{ env.REGION_TO_SUBNET }}' | jq -r --arg key "${{ env.AWS_ENVIRONMENT_REGION }}" '.[$key]')
+          if [[ $VALUE == "null" || $VALUE == "" ]]; then
+            echo "Key '${{ env.AWS_ENVIRONMENT_REGION }}' not found in ${{ env.REGION_TO_SUBNET }}"
+            exit 1
+          fi
+          echo "SUBNET_ID=$VALUE" >> $GITHUB_ENV
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: ${{ env.AWS_ENVIRONMENT_REGION }}
+          role-to-assume: ${{ env.AWS_ROLE_ARN }}
+          role-session-name: ReleaseConcordiumNodeImageSession
+      - name: Download file from S3
+        run: |
+          aws s3 cp s3://distribution.${{ matrix.env }}.concordium.${{ matrix.tld }}/deb/concordium-${{ matrix.env }}-node_${{ env.CONCORDIUM_NODE_VERSION }}_amd64.deb ./concordium-node.deb
+      - name: Setup image name
+        run: |
+          if [ "${{ matrix.cloud_provider }}" == "aws" ]; then
+            echo "IMAGE_NAME=${{ matrix.env }}-${{ env.CONCORDIUM_NODE_VERSION }}-concordium-node-${{ env.OBSERVABILITY_VERSION }}-x86_64" >> $GITHUB_ENV
+          elif [ "${{ matrix.cloud_provider }}" == "gcp" ]; then
+            VERSION_TRANSFORMED=${CONCORDIUM_NODE_VERSION//./-}
+            echo "IMAGE_NAME=${{ matrix.env }}-v$VERSION_TRANSFORMED-concordium-node-${{ env.OBSERVABILITY_VERSION }}-x86-64" >> $GITHUB_ENV
+          else
+            echo "Unknown cloud provider: ${{ matrix.cloud_provider }}"
+            exit 1
+          fi
+      - name: Test if image exists
+        run: |
+          if [ "${{ matrix.cloud_provider }}" == "aws" ]; then
+            echo "IMAGE_ID=$(aws ec2 describe-images --filters Name=name,Values=$IMAGE_NAME --query 'Images[*].ImageId' --output text)" >> $GITHUB_ENV
+          elif [ "${{ matrix.cloud_provider }}" == "gcp" ]; then
+            echo "IMAGE_ID=$(gcloud compute images list --project="concordium-${{ matrix.env }}-0" --filter="name=($IMAGE_NAME)" --format="value(name)")" >> $GITHUB_ENV
+          else
+            echo "Unknown cloud provider: ${{ matrix.cloud_provider }}"
+            exit 1
+          fi
+      - name: Set source image id
+        if: ${{ env.IMAGE_ID == '' }}
+        run: |
+          if [ "${{ matrix.cloud_provider }}" == "aws" ]; then
+            SOURCE_IMAGE_ID=$(aws ec2 describe-images --filters Name=name,Values=concordium-observability-node-${{ env.OBSERVABILITY_VERSION }}-x86_64 --query 'Images[*].ImageId' --output text)
+          elif [ "${{ matrix.cloud_provider }}" == "gcp" ]; then
+            SOURCE_IMAGE_ID=$(gcloud compute images list --project="concordium-mgmt-0" --filter="name=(concordium-observability-node-${{ env.OBSERVABILITY_VERSION }}-x86-64)" --format="value(name)")
+          else
+            echo "Unknown cloud provider: ${{ matrix.cloud_provider }}"
+            exit 1
+          fi
+          echo "SOURCE_IMAGE_ID=$SOURCE_IMAGE_ID" >> $GITHUB_ENV
 
-    - name: Packer concordium-node init
-      if: ${{ env.IMAGE_ID == '' }}
-      run: packer init concordium-node
-    - name: Set variables
-      if: ${{ env.IMAGE_ID == '' }}
-      run: |
-        export CLOUD_PROVIDER=${{ matrix.cloud_provider }}
-        export ENVIRONMENT=${{ matrix.env }}
-        export CONCORDIUM_NODE_PATH=./concordium-node.deb
-        export AWS_SUBNET_ID=${{ env.SUBNET_ID }}
-        export AMI_USERS='${{ matrix.ami_users }}'
-        if [ "$AMI_USERS" == "" ]; then
-          export AMI_USERS='[]'
-        fi
-        envsubst < concordium-node/variables.pkrvars.hcl.template > variables.pkrvars.hcl
-    - name: Build concordium-node image
-      if: ${{ env.IMAGE_ID == '' }}
-      run: packer build -var-file=./variables.pkrvars.hcl concordium-node
-    - name: Output image name
-      if: ${{ env.IMAGE_ID == '' }}
-      id: image_name
-      run: |
-        echo "image_name_${{ matrix.cloud_provider }}_${{ matrix.env }}=$IMAGE_NAME" >> $GITHUB_OUTPUT
+      - name: Packer concordium-node init
+        if: ${{ env.IMAGE_ID == '' }}
+        run: packer init concordium-node
+      - name: Set variables
+        if: ${{ env.IMAGE_ID == '' }}
+        run: |
+          export CLOUD_PROVIDER=${{ matrix.cloud_provider }}
+          export ENVIRONMENT=${{ matrix.env }}
+          export CONCORDIUM_NODE_PATH=./concordium-node.deb
+          export AWS_SUBNET_ID=${{ env.SUBNET_ID }}
+          export AMI_USERS='${{ matrix.ami_users }}'
+          if [ "$AMI_USERS" == "" ]; then
+            export AMI_USERS='[]'
+          fi
+          envsubst < concordium-node/variables.pkrvars.hcl.template > variables.pkrvars.hcl
+      - name: Build concordium-node image
+        if: ${{ env.IMAGE_ID == '' }}
+        run: packer build -var-file=./variables.pkrvars.hcl concordium-node
+      - name: Output image name
+        if: ${{ env.IMAGE_ID == '' }}
+        id: image_name
+        run: |
+          echo "image_name_${{ matrix.cloud_provider }}_${{ matrix.env }}=$IMAGE_NAME" >> $GITHUB_OUTPUT
 
 #  notify-slack-changes:
 #    needs: [release-observability-image, release-concordium-node-image]
